#pragma once

// toolbar
#define TOOLBAR_LABEL "Unreal Auto Setup (All-in-One)"
#define TOOLBAR_LABEL_TIP "Run the Unreal Auto Setup to apply the Shader, Control Rig, and Live Link Blueprint."

#define TOOLBAR_SECTION_AUTOSETUP "Unreal Auto Setup (All-in-One)"
#define TOOLBAR_AUTOSETUP_LL_ORIGIN "Create Live Link Origin"
#define TOOLBAR_AUTOSETUP_LL_ORIGIN_TIP "Create a Live Link Origin in the scene."
#define TOOLBAR_AUTOSETUP_LL_CREATE_BP "Create Live Link Blueprint"
#define TOOLBAR_AUTOSETUP_LL_CREATE_BP_TIP "Create a Live Link Blueprint for the selected asset."
#define TOOLBAR_AUTOSETUP_LL_CREATE_BP_CAMERA "Cine Camera"
#define TOOLBAR_AUTOSETUP_LL_CREATE_BP_CAMERA_TIP "Create a Cine Camera in the scene."
#define TOOLBAR_AUTOSETUP_LL_CREATE_BP_SPOTLIGHT "Spotlight"
#define TOOLBAR_AUTOSETUP_LL_CREATE_BP_SPOTLIGHT_TIP "Create a Spotlight in the scene."
#define TOOLBAR_AUTOSETUP_LL_CREATE_BP_POINTLIGHT "Point Light"
#define TOOLBAR_AUTOSETUP_LL_CREATE_BP_POINTLIGHT_TIP "Create a Point Light in the scene."
#define TOOLBAR_AUTOSETUP_LL_CREATE_BP_RECTLIGHT "Rect Light"
#define TOOLBAR_AUTOSETUP_LL_CREATE_BP_RECTLIGHT_TIP "Create a Rect Light in the scene."
#define TOOLBAR_AUTOSETUP_LL_CREATE_BP_DIRECTLIGHT "Directional Light"
#define TOOLBAR_AUTOSETUP_LL_CREATE_BP_DIRECTLIGHT_TIP "Create a Directional Light in the scene."
#define TOOLBAR_AUTOSETUP_LL_APPLY_BP "Apply Live Link Blueprint"
#define TOOLBAR_AUTOSETUP_LL_APPLY_BP_TIP "Apply the Live Link Blueprint to the selected assets."
#define TOOLBAR_AUTOSETUP_LL_APPLY_BP_CAMERA "Selected Camera(s)"
#define TOOLBAR_AUTOSETUP_LL_APPLY_BP_CAMERA_TIP "Apply the Live Link Blueprint to the selected camera(s)."
#define TOOLBAR_AUTOSETUP_LL_APPLY_BP_LIGHT "Selected Light(s)"
#define TOOLBAR_AUTOSETUP_LL_APPLY_BP_LIGHT_TIP "Apply the Live Link Blueprint to the selected light(s)."
#define TOOLBAR_AUTOSETUP_LL_TRANSFER "Transfer to iClone"
#define TOOLBAR_AUTOSETUP_LL_TRANSFER_TIP "Transfer the assets to iClone."
#define TOOLBAR_AUTOSETUP_LL_TRANSFER_NORMAL "Transfer to iClone"
#define TOOLBAR_AUTOSETUP_LL_TRANSFER_NORMAL_TIP "Transfer assets to iClone."
#define TOOLBAR_AUTOSETUP_LL_TRANSFER_MERGED "Transfer to iClone (Merged)"
#define TOOLBAR_AUTOSETUP_LL_TRANSFER_MERGED_TIP "Transfer the merged assets to iClone."
#define TOOLBAR_AUTOSETUP_LL_TRANSFER_SIMPLIFIED "Transfer to iClone (Simplified)"
#define TOOLBAR_AUTOSETUP_LL_TRANSFER_SIMPLIFIED_TIP "Transfer the simplified assets to iClone."

#define TOOLBAR_SECTION_HELP  "Learn"
#define TOOLBAR_HELP_DOWNLOAD "Product Page"
#define TOOLBAR_HELP_DOWNLOAD_TIP "Product Page"
#define TOOLBAR_HELP_DOWNLOAD_URL "https://www.reallusion.com/linkcount/linkcount.aspx?lid=AS2_001"
#define TOOLBAR_HELP_MANUAL   "Online Manual"
#define TOOLBAR_HELP_MANUAL_TIP   "Online Manual"
#define TOOLBAR_HELP_MANUAL_URL   "https://www.reallusion.com/linkcount/linkcount.aspx?lid=AS2_002"
#define TOOLBAR_HELP_TUTORIAL "Video Tutorials"
#define TOOLBAR_HELP_TUTORIAL_TIP "Video Tutorials"
#define TOOLBAR_HELP_TUTORIAL_URL "https://www.reallusion.com/linkcount/linkcount.aspx?lid=AS2_003"

// right click
#define RIGHT_CLICK_SECTION_CC_TO_METAHUMAN "CC To MetaHuman"
#define RIGHT_CLICK_CC_TO_METAHUMAN_CC_TEXTURE "Apply CC Textures"
#define RIGHT_CLICK_CC_TO_METAHUMAN_CC_TEXTURE_TIP "Apply Character Creator textures to the selected MetaHuman."

#define RIGHT_CLICK_SECTION_AUTOSETUP "Unreal Auto Setup (All-in-One)"
#define RIGHT_CLICK_AUTOSETUP_EXECUTE "Run Unreal Auto Setup"
#define RIGHT_CLICK_AUTOSETUP_EXECUTE_TIP "Run the Unreal Auto Setup to apply the Shader, Control Rig, and Live Link Blueprint."

#define RIGHT_CLICK_CREATE_CC_GROOM "Create CC Groom Binding"
#define RIGHT_CLICK_CREATE_CC_GROOM_TIP "Create a CC Groom binding for the selected character."

#define RIGHT_CLICK_EXPORT_FACIAL_ANIM "Export CC/IC Facial Animation"
#define RIGHT_CLICK_EXPORT_FACIAL_ANIM_TIP "Export CC/IC Facial Animation."

// dialog
#define DIALOG_TITLE_CC_TEXTURE "Apply CC Textures"
#define DIALOG_MESSAGE_CC_TEXTURE_MISSING "To complete this operation, the MetaHuman textures must be present. You should verify that you have saved the character's skeletal mesh or applied the exported data via Character Creator's Export Head (with Target set to Mesh to MetaHuman). "
#define DIALOG_MESSAGE_CC_TEXTURE_SUCCESS "Apply successfully."

#define DIALOG_TITLE_AUTOSETUP "Character Creator & iClone Auto Setup (All-in-One) Import Options"
#define DIALOG_CHECKBOX_AUTOSETUP_ENABLE_AUTOSETUP "Enable Character Creator & iClone Auto Setup (All-in-One)"
#define DIALOG_TEXT_AUTOSETUP_ENABLE_AUTOSETUP_TIP "You should check this option for FBX files from Character Creator (CC) or iClone.\nThe shader type will automatically be set to HQ Shader whenever possible."
#define DIALOG_CHECKBOX_AUTOSETUP_ENABLE_CONTROLRIG "Include Control Rig"
#define DIALOG_CHECKBOX_AUTOSETUP_ENABLE_CONTROLRIG_URL "https://www.reallusion.com/linkcount/linkcount.aspx?lid=AS2_004"
#define DIALOG_CHECKBOX_AUTOSETUP_ENABLE_CONTROLRIG_TIP "Importing the CC Control Rig will take additional time. Check out the <a id=\"link\">Online Manual</> for more information."
#define DIALOG_BUTTON_AUTOSETUP_OK "OK"
#define DIALOG_BUTTON_AUTOSETUP_CANCEL "Cancel"
#define DIALOG_BUTTON_AUTOSETUP_MORE "More"
#define DIALOG_BUTTON_AUTOSETUP_MORE_URL "https://www.reallusion.com/linkcount/linkcount.aspx?lid=AS2_005"

#define DIALOG_MESSAGE_DETECT_OLD_PLUGIN "Character Creator & iClone Auto Setup (All-in-One) detects installed older versions of the Control Rig or Live Link plugins and will automatically disable them."